using System.IO;
using UnityEngine;

/*
 * Represents settings that are loaded in on startup. Useful for dynamically loading offsets, other settings.
 * Application-specific, it lives in the Datapath
 * These are initially generated by the current -settings- on build, nd extracted from a text file on startup.
 * 
 * TODO: Make a Distinction on Editor and Build Config Settings>
 * 
 * @author
 * max@senseglove.com
 */

namespace SG
{

    public class SG_ConfigSettings
    {
        public const string filename = "senseglove.ini";

        private static bool configLoaded = false;
        private static SGConfigBlock loadedConfig = new SGConfigBlock();

        public static string GetFileLocation()
        {
#if UNITY_EDITOR
            return System.IO.Path.Combine(Application.dataPath, filename);
#elif UNITY_STANDALONE_WIN
            //windows
            return Path.Combine( Directory.GetParent(Application.dataPath).FullName, filename );
#else
            return Path.Combine( Application.persistentDataPath, filename );
#endif
        }

        /// <summary> Attempts to load the file if we haven't already. </summary>
        public static void TryLoadConfig()
        {
            if (configLoaded)
                return;
            LoadConfigFile();
        }


        /// <summary> Actively loads the file if one exists </summary>
        public static void LoadConfigFile()
        {
            //can be done at any time.
            configLoaded = true;

#if UNITY_EDITOR
            StoreConfigFile(); // Since you can still directly edit these in the SG Settings Menu in the Editor, we'll only update it to the latest version (so you can copy it over later).
#else
            try
            {
                string filePath = GetFileLocation();
                if (!System.IO.File.Exists(filePath))
                {
                    StoreConfigFile(); //ensure we create one on first launch.
                }
                else
                {
                    SGConfigBlock config = new SGConfigBlock(); 
                    string json = System.IO.File.ReadAllText(filePath);
                    JsonUtility.FromJsonOverwrite(json, config);
                    loadedConfig = config; //only copy if this didn't cause an error.

                    //Log("Loaded Config : " + json);

                    SG_UnitySettings sett = SG_Core.Settings;
                    sett.customPosOffsetRight = config.customPosOffsetRight;
                    sett.customRotOffsetRight = config.customRotOffsetRight;
                    sett.customPosOffsetLeft = config.customPosOffsetLeft;
                    sett.customRotOffsetLeft = config.customRotOffsetLeft;
                    sett.SGCommunications = (CommunicationSetup)config.CommunicationMode;
                    sett.WristTrackingMethod = (GlobalWristTracking)config.WristTrackingMethod;

                    TrackingHardware hw = FromTrackerString(config.TrackingHardware);
                    if (config.TrackingHardware != null && config.TrackingHardware.Length > 0 && hw != TrackingHardware.Unknown)
                    {
                        sett.GlobalWristTrackingOffsets = hw; //catch an exception where there was an issue with the tracking hardware
                    }
                    else
                    {
                        sett.GlobalWristTrackingOffsets = (System.Enum.IsDefined(typeof(TrackingHardware), config.FallbackTrackerOffsets)) ?
                            (TrackingHardware)config.FallbackTrackerOffsets : TrackingHardware.PromptUser;
                    }
                }
            }
            catch (System.Exception ex)
            {
                Debug.LogError($"Error loading config!\n{ex.Message}");
            }
#endif
        }



        public static string ToTrackerString(TrackingHardware hw)
        {
            switch (hw)
            {
                case TrackingHardware.PicoMotionTracker:
                    return "Pico Motion Tracker";
                case TrackingHardware.PicoNeo3Controller:
                    return "Pico Neo 3 Controller";
                case TrackingHardware.PicoNeo2Controller:
                    return "Pico Neo 2 Controller";

                case TrackingHardware.ViveFocus3Tracker:
                    return "Vive Wrist Tracker";
                case TrackingHardware.ViveUltimateTracker:
                    return "Vive Ultimate Tracker";
                case TrackingHardware.ViveTracker:
                    return "Vive Tracker";

                case TrackingHardware.Quest3Controller:
                    return "Quest 3 Controller";
                case TrackingHardware.QuestProController:
                    return "Quest Pro Controller";
                case TrackingHardware.Quest2Controller:
                    return "Quest 2 Controller";

                case TrackingHardware.Custom:
                    return "Custom";
                case TrackingHardware.AutoDetect:
                    return "Auto Detect";
                case TrackingHardware.Unknown:
                    return "Unknown";
                case TrackingHardware.PromptUser:
                    return "Prompt User";

                default:
                    return "";
            }
        }

        public static TrackingHardware FromTrackerString(string hwName)
        {
            if (hwName == null || hwName.Length == 0)
                return TrackingHardware.Unknown;

            string hw = hwName.ToLower();
            switch (hw)
            {
                case "quest 3 controller":
                    return TrackingHardware.Quest3Controller;
                case "quest 2 controller":
                    return TrackingHardware.Quest2Controller;
                case "quest pro controller":

                    return TrackingHardware.QuestProController;
                case "pico motion tracker":
                case "pico neo 3 controller":
                    return TrackingHardware.PicoNeo3Controller;
                case "pico neo 2 controller":
                    return TrackingHardware.PicoNeo2Controller;

                    return TrackingHardware.PicoMotionTracker;
                case "vive wrist tracker":
                    return TrackingHardware.ViveFocus3Tracker;
                case "vive ultimate tracker":
                    return TrackingHardware.ViveUltimateTracker;
                case "vive tracker":
                    return TrackingHardware.ViveTracker;

                //ignoring auto-detect and prompt user so they will be forced back?
                case "custom":
                    return TrackingHardware.Custom;
                case "auto detect":
                    return TrackingHardware.AutoDetect;
                case "prompt user":
                    return TrackingHardware.PromptUser;
                default:
                    return TrackingHardware.Unknown;
            }

        }





        /// <summary> Stores everything currently in the Settings in a Config File </summary>
        public static void StoreConfigFile()
        {

            SG_UnitySettings sett = SG_Core.Settings;

            loadedConfig = new SGConfigBlock(); //TODO: Fill this with the correct values
            loadedConfig.customPosOffsetRight = sett.customPosOffsetRight;
            loadedConfig.customRotOffsetRight = sett.customRotOffsetRight;
            loadedConfig.customPosOffsetLeft = sett.customPosOffsetLeft;
            loadedConfig.customRotOffsetLeft = sett.customRotOffsetLeft;
            loadedConfig.CommunicationMode = (int)sett.SGCommunications;
            loadedConfig.WristTrackingMethod = (int)sett.WristTrackingMethod;

            loadedConfig.FallbackTrackerOffsets = (int)sett.GlobalWristTrackingOffsets;
            loadedConfig.TrackingHardware = ToTrackerString(sett.GlobalWristTrackingOffsets);

            try
            {
                string json = JsonUtility.ToJson(loadedConfig, true);
                string filePath = GetFileLocation();
                string dir = System.IO.Path.GetDirectoryName(filePath);
                if (!System.IO.Directory.Exists(dir))
                    System.IO.Directory.CreateDirectory(dir);
                //Debug.Log("Saving Config: " + json);
                System.IO.File.WriteAllText(filePath, json);
            }
            catch (System.Exception ex)
            {
                Debug.LogError($"Error storing config!\n{ex.Message}");
            }
        }


        private static TrackingHardware s_trackingHW = TrackingHardware.Unknown;

        public static TrackingHardware StoredTrackingHarware
        {
            get 
            {
                TryLoadConfig();
                return s_trackingHW;
            }
            set 
            {
                s_trackingHW = value;
                StoreConfigFile();
            }
        }

        //Since you can directly edit these and I want to convert some things, I use this little data block only for the initial I/O
        [System.Serializable]
        public class SGConfigBlock
        {
            public int CommunicationMode = 0; //SenseCom = 0, Standalone = 1, Disabled = 2

            public int WristTrackingMethod = 0; //0 = UnityXR, 1 = UseGameObjects

            public string TrackingHardware = ""; //name ish

            public int FallbackTrackerOffsets = 0; //when TrackingHardware fails.

            public Vector3 customPosOffsetRight = Vector3.zero;
            public Vector3 customRotOffsetRight = Vector3.zero;

            public Vector3 customPosOffsetLeft = Vector3.zero;
            public Vector3 customRotOffsetLeft = Vector3.zero;
        }
    }
}